version: '3.8'

services:
  # Frontend application
  app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - supabase
    networks:
      - dogoods-network

  # Supabase local development
  supabase:
    image: supabase/supabase-dev
    ports:
      - "54321:54321"  # API
      - "54322:54322"  # Database
      - "54323:54323"  # Studio
      - "54324:54324"  # Inbucket (email testing)
    environment:
      - POSTGRES_PASSWORD=your-super-secret-and-long-postgres-password
      - JWT_SECRET=your-super-secret-jwt-token-with-at-least-32-characters-long
      - ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
    volumes:
      - supabase_data:/var/lib/postgresql/data
      - ./supabase:/supabase
    networks:
      - dogoods-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dogoods-network

volumes:
  supabase_data:
  redis_data:

networks:
  dogoods-network:
    driver: bridge 