/**
 * useFormVoiceGuide
 *
 * Drives a step-by-step spoken guide on any form.
 * Audio is generated by the backend AI TTS endpoint (OpenAI voice).
 * Falls back to browser SpeechSynthesis if the API is unavailable.
 */
import { useState, useEffect, useRef, useCallback } from 'react'
import { textToSpeech, playAudioBlob } from '../utils/openaiVoice'

export default function useFormVoiceGuide({ steps = [], formData = {}, lang = 'en' }) {
  const [isMuted, setIsMuted] = useState(false)
  const [isSpeaking, setIsSpeaking] = useState(false)
  const [isDismissed, setIsDismissed] = useState(false)
  // stopRef holds the stop() fn returned by playAudioBlob so we can cancel mid-playback
  const stopRef = useRef(null)
  const spokenStepRef = useRef(-1)

  // Determine which step is active: the first unfilled step
  const activeIndex = steps.findIndex((s) => !s.isFilled(formData))
  const effectiveIndex = activeIndex === -1 ? steps.length : activeIndex
  const isComplete = effectiveIndex >= steps.length
  const currentStep = isComplete
    ? null
    : { ...steps[effectiveIndex], index: effectiveIndex, total: steps.length }

  // speakText: call backend AI TTS, fall back to browser SpeechSynthesis on error
  const speakText = useCallback(async (text) => {
    if (!text) return
    // Stop any currently playing audio
    if (stopRef.current) { stopRef.current(); stopRef.current = null }

    try {
      const blob = await textToSpeech(text, { lang })
      const { stop } = playAudioBlob(
        blob,
        () => setIsSpeaking(true),
        () => { setIsSpeaking(false); stopRef.current = null },
      )
      stopRef.current = stop
    } catch {
      // Fallback: browser SpeechSynthesis if AI TTS is unavailable
      const synth = typeof window !== 'undefined' ? window.speechSynthesis : null
      if (!synth) return
      synth.cancel()
      const utt = new SpeechSynthesisUtterance(text)
      utt.lang = lang === 'es' ? 'es-ES' : 'en-US'
      utt.rate = 0.95
      utt.onstart = () => setIsSpeaking(true)
      utt.onend = () => setIsSpeaking(false)
      utt.onerror = () => setIsSpeaking(false)
      synth.speak(utt)
    }
  }, [lang])

  const speak = useCallback((text) => {
    const msg = text || currentStep?.instruction || ''
    if (msg) speakText(msg)
  }, [currentStep, speakText])

  // Auto-advance: speak whenever the active step index changes
  useEffect(() => {
    if (isDismissed || isMuted) return
    if (isComplete) return
    if (effectiveIndex === spokenStepRef.current) return

    spokenStepRef.current = effectiveIndex

    const timer = setTimeout(() => {
      speakText(steps[effectiveIndex]?.instruction || '')
    }, 600)
    return () => clearTimeout(timer)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [effectiveIndex, isDismissed, isMuted, isComplete, speakText])

  // Stop audio on unmount
  useEffect(() => {
    return () => { if (stopRef.current) stopRef.current() }
  }, [])

  const toggleMute = useCallback(() => {
    setIsMuted((m) => {
      if (!m && stopRef.current) { stopRef.current(); stopRef.current = null }
      return !m
    })
  }, [])

  const dismiss = useCallback(() => {
    if (stopRef.current) { stopRef.current(); stopRef.current = null }
    setIsDismissed(true)
  }, [])

  return {
    currentStep,
    isComplete,
    isMuted,
    isSpeaking,
    isDismissed,
    toggleMute,
    speak,
    dismiss,
  }
}

// ---------------------------------------------------------------------------
// Step definitions for each form
// ---------------------------------------------------------------------------

/** Share Food (FoodForm) — ordered required fields */
export const SHARE_FOOD_STEPS = [
  {
    id: 'donor_name',
    instruction: 'Let\'s get started! First, enter your name or organization name in the Donor Information section.',
    isFilled: (f) => Boolean(String(f.donor_name || '').trim()),
  },
  {
    id: 'donor_type',
    instruction: 'Great! Now select your donor type — Individual or Organization.',
    isFilled: (f) => Boolean(f.donor_type),
  },
  {
    id: 'full_address',
    instruction: 'Enter the full pickup address so people can find your food on the map.',
    isFilled: (f) => Boolean(String(f.full_address || '').trim()),
  },
  {
    id: 'title',
    instruction: 'What food are you donating? Enter a short, clear name for the item.',
    isFilled: (f) => Boolean(String(f.title || '').trim()),
  },
  {
    id: 'category',
    instruction: 'Select a category for the food — for example, Fresh Produce, Dairy, or Bakery.',
    isFilled: (f) => Boolean(f.category),
  },
  {
    id: 'quantity',
    instruction: 'How much do you have? Enter the quantity and choose a unit like pounds or kilograms.',
    isFilled: (f) => Boolean(f.quantity) && Number(f.quantity) > 0,
  },
  {
    id: 'expiry_date',
    instruction: 'Enter the expiration or best-before date so recipients know how fresh the food is.',
    isFilled: (f) => f.category === 'produce' || Boolean(f.expiry_date),
  },
  {
    id: 'image',
    instruction: 'Almost done! Upload a real photo of the food — no stock images. Then hit Submit.',
    isFilled: (f) => Boolean(f.image) || Boolean(f.image_url),
  },
]

/** Request Food (RequestFoodForm) */
export const REQUEST_FOOD_STEPS = [
  {
    id: 'title',
    instruction: 'Tell the community what food you need. Enter the name or type of food.',
    isFilled: (f) => Boolean(String(f.title || '').trim()),
  },
  {
    id: 'category',
    instruction: 'Select a category that best describes the food you\'re looking for.',
    isFilled: (f) => Boolean(f.category),
  },
  {
    id: 'quantity',
    instruction: 'How much do you need? Enter the quantity and pick a unit.',
    isFilled: (f) => Boolean(f.quantity) && Number(f.quantity) > 0,
  },
  {
    id: 'school_district',
    instruction: 'Choose your school or community so donors near you can see your request.',
    isFilled: (f) => Boolean(String(f.school_district || '').trim()),
  },
  {
    id: 'requester_name',
    instruction: 'Enter your name so donors know who the request is from.',
    isFilled: (f) => Boolean(String(f.requester_name || '').trim()),
  },
  {
    id: 'requester_email',
    instruction: 'Last step — enter your email address, then submit your request.',
    isFilled: (f) => Boolean(String(f.requester_email || '').trim()),
  },
]

/** Claim Food (ClaimFoodForm) — only one interactive step */
export const CLAIM_FOOD_STEPS = [
  {
    id: 'claimQty',
    instruction: 'Use the plus and minus buttons to choose how many portions you need, then press Confirm Claim.',
    isFilled: (f) => Boolean(f.hasConfirmed),
  },
]
