/**
 * useFormVoiceGuide
 *
 * Drives a step-by-step spoken guide on any form.
 * Audio is generated by the backend AI TTS endpoint (OpenAI voice).
 * Falls back to browser SpeechSynthesis if the API is unavailable.
 */
import { useState, useEffect, useRef, useCallback } from 'react'
import { textToSpeech, playAudioBlob } from '../utils/openaiVoice'

export default function useFormVoiceGuide({ steps = [], formData = {}, lang = 'en', hints = {} }) {
  const [isMuted, setIsMuted] = useState(false)
  const [isSpeaking, setIsSpeaking] = useState(false)
  const [isDismissed, setIsDismissed] = useState(false)
  // stopRef holds the stop() fn returned by playAudioBlob so we can cancel mid-playback
  const stopRef = useRef(null)
  const spokenStepRef = useRef(-1)

  // Determine which step is active: the first unfilled step
  const activeIndex = steps.findIndex((s) => !s.isFilled(formData))
  const effectiveIndex = activeIndex === -1 ? steps.length : activeIndex
  const isComplete = effectiveIndex >= steps.length
  const currentStep = isComplete
    ? null
    : { ...steps[effectiveIndex], index: effectiveIndex, total: steps.length }

  // speakText: call backend AI TTS, fall back to browser SpeechSynthesis on error
  const speakText = useCallback(async (text) => {
    if (!text) return
    // Stop any currently playing audio
    if (stopRef.current) { stopRef.current(); stopRef.current = null }

    try {
      const blob = await textToSpeech(text, { lang })
      const { stop } = playAudioBlob(
        blob,
        () => setIsSpeaking(true),
        () => { setIsSpeaking(false); stopRef.current = null },
      )
      stopRef.current = stop
    } catch {
      // Fallback: browser SpeechSynthesis if AI TTS is unavailable
      const synth = typeof window !== 'undefined' ? window.speechSynthesis : null
      if (!synth) return
      synth.cancel()
      const utt = new SpeechSynthesisUtterance(text)
      utt.lang = lang === 'es' ? 'es-ES' : 'en-US'
      utt.rate = 0.95
      utt.onstart = () => setIsSpeaking(true)
      utt.onend = () => setIsSpeaking(false)
      utt.onerror = () => setIsSpeaking(false)
      synth.speak(utt)
    }
  }, [lang])

  const speak = useCallback((text) => {
    const msg = text || currentStep?.instruction || ''
    if (msg) speakText(msg)
  }, [currentStep, speakText])

  // Auto-advance: speak whenever the active step index changes
  useEffect(() => {
    if (isDismissed || isMuted) return
    if (isComplete) return
    if (effectiveIndex === spokenStepRef.current) return

    spokenStepRef.current = effectiveIndex

    const timer = setTimeout(() => {
      speakText(steps[effectiveIndex]?.instruction || '')
    }, 600)
    return () => clearTimeout(timer)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [effectiveIndex, isDismissed, isMuted, isComplete, speakText])

  // Stop audio on unmount
  useEffect(() => {
    return () => { if (stopRef.current) stopRef.current() }
  }, [])

  const toggleMute = useCallback(() => {
    setIsMuted((m) => {
      if (!m && stopRef.current) { stopRef.current(); stopRef.current = null }
      return !m
    })
  }, [])

  const dismiss = useCallback(() => {
    if (stopRef.current) { stopRef.current(); stopRef.current = null }
    setIsDismissed(true)
  }, [])

  // speakField — called on field focus; speaks the field-specific hint
  const speakField = useCallback((fieldName) => {
    if (isMuted || isDismissed) return
    const hint = hints[fieldName]
    if (hint) speakText(hint)
  }, [isMuted, isDismissed, speakText, hints])

  return {
    currentStep,
    isComplete,
    isMuted,
    isSpeaking,
    isDismissed,
    toggleMute,
    speak,
    dismiss,
    speakField,
  }
}

// ---------------------------------------------------------------------------
// Per-field focus hints — spoken when the user clicks/tabs into a field
// ---------------------------------------------------------------------------

export const SHARE_FOOD_HINTS = {
  donor_name:       'Enter your full name, or the name of your organization if you\'re donating on behalf of one.',
  donor_type:       'Choose Individual or Family if you\'re donating personally, or Organization if you represent a business or group.',
  donor_zip:        'Enter the ZIP code for your pickup location.',
  donor_city:       'Enter the city where the food can be picked up.',
  donor_state:      'Select the state where pickup will happen.',
  school_district:  'Choose the community or school this donation belongs to.',
  donor_email:      'Enter your email address so recipients can contact you if needed.',
  donor_phone:      'Optional — add a phone number if you\'d like to be reachable by phone.',
  full_address:     'Enter the complete street address for pickup. We\'ll pin it on the map automatically.',
  donor_occupation: 'Optional — your occupation or role, for example Teacher or Chef.',
  title:            'Give the food a short, clear name. For example: Apples, Rice, or Homemade Bread.',
  category:         'Pick the category that best fits the food — such as Fresh Produce, Dairy, or Bakery.',
  description:      'Describe the food in a few sentences — its condition, source, and any details recipients should know.',
  quantity:         'Enter how much food you have, then choose a unit like pounds, kilograms, or count.',
  unit:             'Choose the unit for the quantity — pounds, kilograms, ounces, or servings.',
  expiry_date:      'Enter the expiration or best-before date so recipients know how fresh the food is.',
  pickup_by:        'Optional — set a specific date and time by which the food must be picked up.',
  dietary_tags:     'Check any labels that apply to this food, such as Vegetarian, Vegan, or Gluten-Free.',
  allergens:        'Check all allergens present so recipients with dietary restrictions can stay safe.',
  ingredients:      'Optional — list the main ingredients, especially if this is a prepared or packaged food.',
  image:            'Upload a real photo of the food. Clear, well-lit photos help recipients decide faster.',
}

export const REQUEST_FOOD_HINTS = {
  title:           'Describe the food you need — for example Rice, Baby Formula, or Fresh Vegetables.',
  category:        'Select the category that best matches the food you\'re looking for.',
  quantity:        'Enter how much you need and choose a unit like items, pounds, or bags.',
  unit:            'Choose the unit for your quantity.',
  needed_by:       'Optional — if you need the food by a specific date, enter it here.',
  school_district: 'Choose your school or community so the right donors can see your request.',
  description:     'Optional — add details like household size, why you need it, or preferred pickup area.',
  dietary_notes:   'Optional — list any dietary needs, such as gluten-free or nut allergy.',
  requester_name:  'Enter your name so donors know who the request is from.',
  requester_email: 'Enter your email address so donors or admins can reach you.',
  requester_phone: 'Optional — add a phone number if you prefer to be contacted by phone.',
  full_address:    'Optional — enter your neighborhood or address to help donors near you.',
}

export const CLAIM_FOOD_HINTS = {
  claimQty: 'Use the plus and minus buttons to choose how many portions you\'d like to claim, then press Confirm Claim.',
}

// ---------------------------------------------------------------------------
// Step definitions for each form
// ---------------------------------------------------------------------------

/** Share Food (FoodForm) — ordered required fields */
export const SHARE_FOOD_STEPS = [
  {
    id: 'donor_name',
    instruction: 'Let\'s get started! First, enter your name or organization name in the Donor Information section.',
    isFilled: (f) => Boolean(String(f.donor_name || '').trim()),
  },
  {
    id: 'donor_type',
    instruction: 'Great! Now select your donor type — Individual or Organization.',
    isFilled: (f) => Boolean(f.donor_type),
  },
  {
    id: 'full_address',
    instruction: 'Enter the full pickup address so people can find your food on the map.',
    isFilled: (f) => Boolean(String(f.full_address || '').trim()),
  },
  {
    id: 'title',
    instruction: 'What food are you donating? Enter a short, clear name for the item.',
    isFilled: (f) => Boolean(String(f.title || '').trim()),
  },
  {
    id: 'category',
    instruction: 'Select a category for the food — for example, Fresh Produce, Dairy, or Bakery.',
    isFilled: (f) => Boolean(f.category),
  },
  {
    id: 'quantity',
    instruction: 'How much do you have? Enter the quantity and choose a unit like pounds or kilograms.',
    isFilled: (f) => Boolean(f.quantity) && Number(f.quantity) > 0,
  },
  {
    id: 'expiry_date',
    instruction: 'Enter the expiration or best-before date so recipients know how fresh the food is.',
    isFilled: (f) => f.category === 'produce' || Boolean(f.expiry_date),
  },
  {
    id: 'image',
    instruction: 'Almost done! Upload a real photo of the food — no stock images. Then hit Submit.',
    isFilled: (f) => Boolean(f.image) || Boolean(f.image_url),
  },
]

/** Request Food (RequestFoodForm) */
export const REQUEST_FOOD_STEPS = [
  {
    id: 'title',
    instruction: 'Tell the community what food you need. Enter the name or type of food.',
    isFilled: (f) => Boolean(String(f.title || '').trim()),
  },
  {
    id: 'category',
    instruction: 'Select a category that best describes the food you\'re looking for.',
    isFilled: (f) => Boolean(f.category),
  },
  {
    id: 'quantity',
    instruction: 'How much do you need? Enter the quantity and pick a unit.',
    isFilled: (f) => Boolean(f.quantity) && Number(f.quantity) > 0,
  },
  {
    id: 'school_district',
    instruction: 'Choose your school or community so donors near you can see your request.',
    isFilled: (f) => Boolean(String(f.school_district || '').trim()),
  },
  {
    id: 'requester_name',
    instruction: 'Enter your name so donors know who the request is from.',
    isFilled: (f) => Boolean(String(f.requester_name || '').trim()),
  },
  {
    id: 'requester_email',
    instruction: 'Last step — enter your email address, then submit your request.',
    isFilled: (f) => Boolean(String(f.requester_email || '').trim()),
  },
]

/** Claim Food (ClaimFoodForm) — only one interactive step */
export const CLAIM_FOOD_STEPS = [
  {
    id: 'claimQty',
    instruction: 'Use the plus and minus buttons to choose how many portions you need, then press Confirm Claim.',
    isFilled: (f) => Boolean(f.hasConfirmed),
  },
]
