"""
Agent State Definitions
========================
TypedDict schemas for LangGraph agent state management.

The agent maintains state across conversation turns, enabling:
- Multi-step plan execution
- Context preservation
- Preference learning
- Proactive suggestions
"""

from typing import TypedDict, List, Dict, Any, Optional, Literal
from datetime import datetime


class Message(TypedDict):
    """Single conversation message."""
    role: Literal["user", "assistant", "system", "tool"]
    content: str
    timestamp: str
    tool_calls: Optional[List[Dict[str, Any]]]
    tool_results: Optional[List[Dict[str, Any]]]


class PlanStep(TypedDict):
    """Single step in a multi-step plan."""
    step_number: int
    action: str
    tool_name: Optional[str]
    tool_args: Optional[Dict[str, Any]]
    status: Literal["pending", "in_progress", "completed", "failed"]
    result: Optional[Any]


class UserContext(TypedDict):
    """User profile and preferences for contextual decision-making."""
    user_id: str
    name: Optional[str]
    location: Optional[Dict[str, float]]  # {latitude, longitude}
    address: Optional[str]
    dietary_restrictions: List[str]
    allergies: List[str]
    preferences: Dict[str, Any]  # Learned preferences
    communities: List[str]
    role: Optional[str]  # donor, recipient, volunteer, etc.


class ProactiveSuggestion(TypedDict):
    """Proactive suggestion generated by the agent."""
    type: Literal["reminder", "opportunity", "tip", "milestone"]
    message: str
    priority: Literal["high", "medium", "low"]
    action_required: bool
    action_label: Optional[str]


class AgentState(TypedDict, total=False):
    """Complete agent state for LangGraph workflow.
    
    This state is persisted to Supabase between conversation turns,
    enabling resumable conversations and contextual awareness.
    """
    # Conversation identity
    conversation_id: str
    user_id: str
    
    # Message history
    messages: List[Message]
    
    # Current turn state
    current_message: str
    detected_intent: Optional[str]
    detected_language: Literal["en", "es"]
    
    # User context
    user_context: UserContext
    
    # Planning & execution
    active_plan: Optional[List[PlanStep]]
    plan_goal: Optional[str]
    current_step: int
    
    # Tool execution results
    recent_tool_results: List[Dict[str, Any]]
    recent_search_results: Optional[List[Dict[str, Any]]]
    
    # Proactive suggestions
    pending_suggestions: List[ProactiveSuggestion]
    
    # Agent decision-making
    should_suggest_proactively: bool
    requires_user_input: bool
    conversation_phase: Literal[
        "understanding",
        "planning", 
        "executing",
        "confirming",
        "completed",
        "idle"
    ]
    
    # Response generation
    response_text: Optional[str]
    include_audio: bool
    audio_url: Optional[str]
    
    # Metadata
    turn_count: int
    last_updated: str
    error: Optional[str]


class ConversationState(TypedDict):
    """Lightweight state for checkpointing to database."""
    conversation_id: str
    user_id: str
    state_snapshot: Dict[str, Any]  # Serialized AgentState
    checkpoint_type: Literal["turn_end", "plan_step", "manual"]
    created_at: str
